version: '3.8'

services:
  #   # MYSQL Database
  ngo_mysql_db:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-P@ssw0rd}'
      - 'MYSQL_DATABASE=${MYSQL_DATABASE:-ngo}'
    ports:
      - '${MYSQL_PORT:-3307}:3307'
    volumes:
      - ngo_mysql_db:/var/lib/mysql

  # Redis
  ngo_redis:
    image: redis:latest
    restart: always
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_volume:/data

  # Postgres Service
  ngo_keycloak_postgres:
    image: postgres:15.2-alpine
    volumes:
      - ngo_keycloak_postgres:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: '${POSTGRES_DB}:-keycloak}'
      POSTGRES_USER: '${POSTGRES_USER:-postgres}'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-P@ssw0rd}

  ngo_keycloak:
    image: quay.io/keycloak/keycloak:21.1
    volumes:
      - ngo_keycloak:/opt/keycloak
    environment:
      DB_VENDOR: POSTGRES
      KC_PROXY: edge
      KC_HOSTNAME_ADMIN_URL: '${KC_HOSTNAME_URL:-http://localhost:8080}'
      KC_HOSTNAME_URL: '${KC_HOSTNAME_URL:-http://localhost:8080}'
      KC_HTTP_ENABLED: '${KC_HTTP_ENABLED:-true}'
      KEYCLOAK_ADMIN: '${KEYCLOAK_ADMIN:-admin}'
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-P@ssw0rd}
      DB_ADDR: postgres  // Set the address of the database to use for keycloak
      DB_DATABASE: '${POSTGRES_DB:-keycloak}'
      DB_USER: '${POSTGRES_USER:-postgres}'
      DB_SCHEMA: public
      DB_PASSWORD: ${POSTGRES_PASSWORD:-P@ssw0rd}
    ports:
      - ${KEYCLOAK_PORT:-8080}:8080
    depends_on:
      - ngo_keycloak_postgres
    command: start

# Defining Volumes
volumes:
  ngo_mysql_db:
    driver: local
  redis_volume:
    driver: local
  ngo_keycloak_postgres:
    driver: local
  ngo_keycloak:
    driver: local